//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basis.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not allow null..
        /// </summary>
        public static string caller_does_not_allow_null {
            get {
                return ResourceManager.GetString("caller_does_not_allow_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not allow null or whitespace..
        /// </summary>
        public static string caller_does_not_allow_null_or_whitespace {
            get {
                return ResourceManager.GetString("caller_does_not_allow_null_or_whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} expected at least one item for {1}..
        /// </summary>
        public static string caller_expected_at_least_one_item_for_x {
            get {
                return ResourceManager.GetString("caller_expected_at_least_one_item_for_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} expected specified values to be in ascending sequence..
        /// </summary>
        public static string caller_expected_specified_values_to_be_in_ascending_sequence {
            get {
                return ResourceManager.GetString("caller_expected_specified_values_to_be_in_ascending_sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires parameter length to be between {1} and {2} characters..
        /// </summary>
        public static string caller_requires_parameter_length_to_be_between_x_and_y_characters {
            get {
                return ResourceManager.GetString("caller_requires_parameter_length_to_be_between_x_and_y_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires value to be between {1} and {2}..
        /// </summary>
        public static string caller_requires_value_to_be_between_x_and_y {
            get {
                return ResourceManager.GetString("caller_requires_value_to_be_between_x_and_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires value to be between {1} and {2} (inclusive)..
        /// </summary>
        public static string caller_requires_value_to_be_between_x_and_y_inclusive {
            get {
                return ResourceManager.GetString("caller_requires_value_to_be_between_x_and_y_inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service of type {0} is not registered..
        /// </summary>
        public static string service_of_type_x_is_not_registered {
            get {
                return ResourceManager.GetString("service_of_type_x_is_not_registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create instance of type {0}..
        /// </summary>
        public static string unable_to_create_instance_of_type_x {
            get {
                return ResourceManager.GetString("unable_to_create_instance_of_type_x", resourceCulture);
            }
        }
    }
}
